apiVersion: s3.services.k8s.aws/v1alpha1
kind: Bucket
metadata:
  name: {{ .Values.bucketNameOverride | default .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  name: {{ .Values.bucketNameOverride | default .Release.Name | quote }}
  publicAccessBlock:
    blockPublicACLs: {{ .Values.publicAccessBlock.blockPublicACLs}}
    blockPublicPolicy: {{ .Values.publicAccessBlock.blockPublicPolicy}}
    ignorePublicACLs: {{ .Values.publicAccessBlock.ignorePublicACLs}}
    restrictPublicBuckets: {{ .Values.publicAccessBlock.restrictPublicBuckets}}
  {{- if eq .Values.bucketType "website" }}
  website:
    errorDocument:
      key: index.html
    indexDocument:
      suffix: 404.html
  {{- end }}
  {{- if eq .Values.bucketType "testing" }}
  lifecycle:
    rules:
      - expiration:
          days: 3
        filter: { }
        id: expire
        status: Enabled
  {{- else if eq .Values.bucketType "production" }}
  lifecycle:
    rules:
      - id: expire-prod
        noncurrentVersionExpiration:
          newerNoncurrentVersions: 3
          noncurrentDays: 30
        filter: { }
        status: Enabled
  {{- end }}
  tagging:
    tagSet:
      - key: "bucket-type"
        value: {{ .Values.bucketType }}
      - key: "bucket-owner"
        value: {{ .Release.Name }}