{{- if ne ((.Values.networking).expose) "none" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ if eq .Values.networking.expose "external" }}LoadBalancer{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ (.Values.networking).port }}
      targetPort: {{ (.Values.networking).port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
{{- end }}
