apiVersion: v1
kind: ConfigMap
metadata:
  name: metabase-config
data:
  MB_DB_TYPE: "postgres"
  MB_DB_DBNAME: "metabase"
  MB_DB_PORT: "5432"
  MB_DB_USER: "user"
  MB_DB_PASS: "pass"
  MB_DB_HOST: "metabase-db"
