apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-metabase-config
data:
  MB_DB_TYPE: {{ .Values.database.type | quote }}
  MB_DB_DBNAME: {{ .Values.database.dbname | quote }}
  MB_DB_PORT: {{ .Values.database.port | quote }}
  MB_DB_USER: {{ .Values.database.user | quote }}
  MB_DB_PASS: {{ .Values.database.pass | quote }}
  MB_DB_HOST: {{ .Values.database.host | quote }}
