apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metabase-service
spec:
  selector:
    app: {{ .Release.Name }}-metabase
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
