---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.persistentVolumeSize }}Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-claim
  namespace: {{ .Values.namespace }}
spec:
  volumeName: {{ .Values.name }}-volume
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeSize }}Gi
