{{- if ((.Values.networking).expose) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ (.Values.networking).port }}
      targetPort: {{ (.Values.networking).port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
  {{- end }}
