apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: mcp
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Values.service }}-mcp
    app.kubernetes.io/part-of: {{ .Values.service }}
  name: {{ .Release.Name }}-{{ .Values.service }}-mcp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Values.service }}-mcp
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-{{ .Values.service }}-mcp
    namespace: {{ .Release.Namespace }}
