apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.service }}-mcp-env-config
  labels:
    app.kubernetes.io/component: mcp
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Values.service }}-mcp
    app.kubernetes.io/part-of: {{ .Values.service }}
data:
  {{- range index .Values.providers .Values.service "env" }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}

  {{- range $key, $value := .Values.environment }}
  - name: {{ $key }}
    value: {{ $value | quote }}
  {{- end }}
