apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/component: mcp
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.service }}
spec:
  replicas: {{ .Values.scaling.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: mcp
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/part-of: {{ .Values.service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: mcp
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Values.service }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Values.service }}-mcp
          image: {{ index .Values.providers .Values.service "image" }}
          {{- $cmd := include "provider.command" . | trim }}
          {{- if $cmd }}
          command: {{ $cmd }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
            {{ if ((.Values.secrets).secretRef).name }}
            - secretRef:
                name: {{ .Values.secrets.secretRef.name }}
            {{- end }}
            - secretRef:
                name: {{ .Release.Name }}
