apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/component: mcp
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.service }}
type: Opaque
data:
  {{ if (.Values.secrets).variables }}
  {{- range $key, $value := .Values.secrets.variables }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{ end }}
