apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.service }}-mcp-env-secret
  labels:
    app.kubernetes.io/component: mcp
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Values.service }}-mcp
    app.kubernetes.io/part-of: {{ .Values.service }}
type: Opaque
data:
  {{- range .Values.secrets.variables }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
