apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: mcp
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Values.service }}-mcp
    app.kubernetes.io/part-of: {{ .Values.service }}
  name: {{ .Release.Name }}-{{ .Values.service }}-mcp
