image: docker.io/mcp/fetch
permissionProfile:
  name: network
  type: builtin
podTemplateSpec:
  spec:
    containers:
      - name: mcp
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
port: 8080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
transport: sse
