service: redis

scaling:
  replicas: 1

permissions:
  enabled: false

port: 8000

providers:
  grafana:
    image: "mcp/grafana"
  wikipedia:
    image: "mcp/wikipedia"
  redis:
    image: "mcp/redis"
    env:
      - name: REDIS_PORT
        value: "6379"
      - name: REDIS_USERNAME
        value: "default"
      - name: REDIS_PWD
        value: ""
      - name: MCP_TRANSPORT
        value: "sse"
