apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-secret
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.username | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.password | b64enc | quote }}
