apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio-service
spec:
  selector:
    app: minio
  ports:
  - protocol: TCP
    port: 80  # External access port
    targetPort: {{ .Values.service.apiPort | default 9000 }}  # API port
  - protocol: TCP
    port: 9090  # Console access port
    targetPort:  {{ .Values.service.consolePort | default 9090 }}
  type: {{ .Values.service.type | default "ClusterIP" }}  # Adjust type for external access
