apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: mcp
    app.kubernetes.io/name: cyclops-mcp
    app.kubernetes.io/part-of: cyclops
  name: cyclops-mcp
  namespace: {{ include "cyclops.namespace" . | quote }}
rules:
  - apiGroups:
      - 'cyclops-ui.com'
    resources:
      - '*'
    verbs:
      - '*'
