apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyclops-mcp
  namespace: {{ include "cyclops.namespace" . | quote }}
  labels:
    app: cyclops-mcp
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: cyclops-mcp
  template:
    metadata:
      labels:
        app: cyclops-mcp
    spec:
      serviceAccountName: cyclops-mcp
      containers:
        - name: cyclops-mcp
          image: {{ printf "cyclopsui/cyclops-mcp:%s" (default .Chart.AppVersion .Values.version) }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            {{- include "watchNamespace" . | nindent 12 }}
