apiVersion: v1
kind: Service
metadata:
  name: cyclops-mcp
  namespace: {{ include "cyclops.namespace" . | quote }}
  labels:
    app: cyclops-mcp
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: cyclops-mcp
