apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: mcp
    app.kubernetes.io/name: cyclops-mcp
    app.kubernetes.io/part-of: cyclops
  name: cyclops-mcp
  namespace: {{ include "cyclops.namespace" . | quote }}
