apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  attributeDefinitions:
    {{- if .Values.attributeDefinitions }}
    {{- range .Values.attributeDefinitions }}
    - attributeName: {{ .attributeName | quote }}
      attributeType: {{ if eq .attributeType "string" }}"S"{{ else if eq .attributeType "boolean" }}"B"{{ else if eq .attributeType "number" }}"N"{{ end }}
    {{- end }}
    {{- else }}
    {{- fail "attributeDefinitions cannot be empty" }}
    {{- end }}
  tableName: {{ .Release.Name | quote }}
  keySchema:
    {{- if .Values.attributeDefinitions }}
    {{- range .Values.attributeDefinitions }}
    - attributeName: {{ .attributeName | quote }}
      keyType: {{ .keyType | quote }}
    {{- end }}
    {{- else }}
    {{- fail "keySchema cannot be empty" }}
    {{- end }}
  provisionedThroughput:
    readCapacityUnits: {{ .Values.provisionedThroughput.readCapacityUnits }}
    writeCapacityUnits: {{ .Values.provisionedThroughput.writeCapacityUnits }}
